simulation:
  name: lowermississippi_rcp85cooler
  start_date: 2020-01-01
  end_date: 2099-12-31
grid:
  path: ./input/domains/mosart_conus_nldas_grid.nc
  subdomain:
  - 33.9375,-91.3125
  - 31.0625,-91.5625
  - 34.1875,-93.1875
  - 34.5625,-93.1875
  - 34.4375,-93.0625
  - 34.4375,-92.9375
  - 34.1875,-93.6875
  unmask_output: false
runoff:
  read_from_file: true
  path: ./input/runoff/rcp85cooler/08/mosart_rcp85cooler_huc08_8th_runoff_{Y}_{M}.nc
water_management:
  enabled: true
  demand:
    read_from_file: true
    path: ./input/demand/RCP8.5_GCAM_water_demand_2020_2099.nc
  reservoirs:
    enable_istarf: true
    parameters:
      path: ./input/reservoirs/reservoirs.nc
    dependencies:
      path: ./input/reservoirs/dependency_database.parquet
    streamflow:
      path: ./input/reservoirs/mean_monthly_reservoir_flow.parquet
    demand:
      path: ./input/reservoirs/mean_monthly_reservoir_demand.parquet
